### ISSUE TITLE
Emoji flash/freakout and typing message visual error

### ISSUE THREAD

**Issue by ShawnPR1** [HansAnonymous/BD-Themes-and-Plugins#2]
When you scroll through your emojis they flash and freak out for a few seconds before appearing normal once more. Another small bug I've encountered is when you are in your direct message panel and are speaking to a friend, the green outline shifts to the right of their profile picture when they are busy typing. (Picture included). This is an amazing theme btw. Only reason why I'm typing this is so it is almost flawless seeing I'll never use a different theme. 
![typing](https://user-images.githubusercontent.com/31240808/29559483-86bfa74a-872f-11e7-90db-d9f835508422.png)

**Comment by HansAnonymous** [comment]
@ShawnPR1 @ShawnPR1 Thanks a ton for the feedback! I'll check those out and see what I can do to fix them! If you could join https://discord.gg/x6h7usC then if there's anything else you can message me on there!

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HansAnonymous** [comment]
I'm not sure if I can fix the emoji flashing issue, but I'll keep looking out for a way to fix it. The typing status is now fixed with the latest update.
