### ISSUE TITLE
Theme seems to be a bit off.

### ISSUE THREAD

**Issue by badbones69** [HansAnonymous/BD-Themes-and-Plugins#3]
The theme looks great for the most part. Seems that some of the stuff seems a bit broke. Could be because I am on a mac or because of the newest discord version. Here is what seems to be off for me.

Discord Version: Sep 21, 2017 Update (Not sure if there even is a version number)
BetterDiscord Version: v0.2.81 for mac

1. Weird Bar at the top.
![Bar](https://image.prntscr.com/image/sjt1bI3cQEeEHodtqHLM8A.png)

2. Profiles seem to be too transparent.
![Profiles](https://image.prntscr.com/image/iOeKJ9tqQrim-vqmWCFDBQ.png)

**Comment by HansAnonymous** [comment]
Those are now fixed :)
